version: '2.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    env_file:
      - ./.env
    restart: always
    init: true
    networks:
      - inception
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - ./.env
    restart: always
    init: true
    networks:
      - inception
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env
    restart: always
    init: true
    networks:
      - inception
networks:
  inception:
    driver: bridge
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mrahmani/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mrahmani/data/wordpress