version: '3.3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - "/home/mrahmani/data/wordpress:/var/www/wordpress"
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - "/home/mrahmani/data/wordpress:/var/www/wordpress"