version: '3.3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - "/home/mrahmani/data/wordpress:/var/www/wordpress"
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - "/home/mrahmani/data/wordpress:/var/www/wordpress"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - "/home/mrahmani/data/mariadb:/var/lib/mysql"